In [ ]:
# prompt: baixe o tensorflow

# !pip install tensorflow


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# prompt: Leia o arquivo npz no caminho: /content/drive/MyDrive/Classroom/IA048 Turma A - 1s2024/Atividade_3/bloodmnist_64.npz

import numpy as np
data = np.load('/content/drive/MyDrive/Classroom/IA048_Turma_A-1s2024/Atividade_3/bloodmnist_64.npz')
print("Chaves disponíveis no arquivo:", data.files)

# Load the arrays from the NPZ file
X_train = data['train_images']
y_train = data['train_labels']
X_val = data['val_images']
y_val = data['val_labels']
X_test = data['test_images']
y_test = data['test_labels']

Chaves disponíveis no arquivo: ['train_images', 'train_labels', 'val_images', 'val_labels', 'test_images', 'test_labels']


In [ ]:
# prompt: Como ver o tamanho de X_train?

print("Tamanho de X_train:", len(X_train))


Tamanho de X_train: 11959


In [ ]:
print(X_train[0], y_train)

[[[254 228 201]
  [254 228 201]
  [253 228 201]
  ...
  [255 231 202]
  [252 226 202]
  [251 225 198]]

 [[254 228 201]
  [254 228 201]
  [253 228 201]
  ...
  [255 231 201]
  [255 230 202]
  [254 230 200]]

 [[254 228 201]
  [254 228 201]
  [254 228 201]
  ...
  [255 232 201]
  [255 232 201]
  [255 232 201]]

 ...

 [[216 176 172]
  [215 176 171]
  [215 177 172]
  ...
  [253 228 201]
  [254 228 201]
  [255 229 202]]

 [[219 180 175]
  [218 179 174]
  [218 180 175]
  ...
  [254 229 202]
  [255 229 202]
  [255 230 203]]

 [[222 187 176]
  [222 187 176]
  [221 185 175]
  ...
  [253 230 202]
  [255 230 203]
  [255 231 204]]] [[7]
 [3]
 [6]
 ...
 [1]
 [6]
 [4]]


In [ ]:
len(y_train)

11959

In [ ]:
y_train[0][0]

7

In [ ]:
# prompt: y_train está como array de vários arrays de um único valor, mas quero que fique como um único array de valores

y_train = np.concatenate(y_train)
# X_train = np.concatenate(X_train)


In [ ]:
# X_val

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint

# Função para criar o modelo Keras
def create_model():
    model = Sequential()
    model.add(Flatten(input_shape=(64, 64, 3)))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(32, activation='softmax'))
    model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Crie o modelo Keras
model = create_model()

# Defina o callback ModelCheckpoint para salvar o melhor modelo
checkpoint_callback = ModelCheckpoint(filepath='best_model.h5', monitor='val_accuracy', save_best_only=True, verbose=1)

# Treine o modelo nos dados de treinamento e validação, usando o callback ModelCheckpoint
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val), callbacks=[checkpoint_callback])

Epoch 1/10
372/374 [============================>.] - ETA: 0s - loss: 224.6215 - accuracy: 0.4420
Epoch 1: val_accuracy improved from -inf to 0.53797, saving model to best_model.h5
374/374 [==============================] - 9s 22ms/step - loss: 224.1864 - accuracy: 0.4424 - val_loss: 133.7085 - val_accuracy: 0.5380
Epoch 2/10
373/374 [============================>.] - ETA: 0s - loss: 94.0066 - accuracy: 0.5680
Epoch 2: val_accuracy did not improve from 0.53797
374/374 [==============================] - 10s 26ms/step - loss: 93.9317 - accuracy: 0.5683 - val_loss: 139.6540 - val_accuracy: 0.4982
Epoch 3/10
373/374 [============================>.] - ETA: 0s - loss: 81.6655 - accuracy: 0.6026
Epoch 3: val_accuracy improved from 0.53797 to 0.66238, saving model to best_model.h5
374/374 [==============================] - 8s 23ms/step - loss: 81.7342 - accuracy: 0.6029 - val_loss: 103.0805 - val_accuracy: 0.6624
Epoch 4/10
372/374 [============================>.] - ETA: 0s - loss: 67.4282 - a

In [ ]:
from tensorflow.keras.models import load_model

# Carregue o melhor modelo salvo
best_model = load_model('best_model.h5')

# Avalie o melhor modelo nos dados de teste
y_test_pred = best_model.predict(X_test)
y_test_pred = np.argmax(y_test_pred, axis=1)
accuracy_test = accuracy_score(y_test, y_test_pred)
confusion_matrix_test = confusion_matrix(y_test, y_test_pred)

# Imprima os resultados
print('Acurácia nos dados de teste:', accuracy_test)
print('Matriz de confusão nos dados de teste:')
print(confusion_matrix_test)

107/107 [==============================] - 0s 4ms/step
Acurácia nos dados de teste: 0.6620871090324466
Matriz de confusão nos dados de teste:
[[165  19  22  10   5  18   5   0]
 [  0 572  27   0   1   0  23   1]
 [ 23   0 223   2   7   2  19  35]
 [200  66  73 123   4  24  87   2]
 [ 17   1  79   0 136   0   8   2]
 [ 66  52   2  78   1  55  28   2]
 [  2  49  79   0   1   0 528   7]
 [  0   0   3   0   0   0   4 463]]


In [ ]:
# # Codigo ChatGPT
# import tensorflow as tf
# from sklearn.metrics import accuracy_score, confusion_matrix
# import numpy as np

# # Suponha que você tenha seus dados de treinamento e teste em X_train, y_train e X_test, y_test, respectivamente

# # Definindo o modelo MLP
# model = tf.keras.Sequential([
#     tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
#     tf.keras.layers.Dense(32, activation='relu'),
#     tf.keras.layers.Dense(1, activation='sigmoid')
# ])

# # Compilando o modelo
# model.compile(optimizer='adam',
#               loss='binary_crossentropy',
#               metrics=['accuracy'])

# # Treinando o modelo
# model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

# # Avaliando a acurácia no conjunto de teste
# y_pred = model.predict_classes(X_test)
# accuracy = accuracy_score(y_test, y_pred)
# print("Acurácia:", accuracy)

# # Calculando a matriz de confusão
# conf_matrix = confusion_matrix(y_test, y_pred)
# print("Matriz de Confusão:")
# print(conf_matrix)

In [ ]:
import numpy as np

# Suponha que você tenha uma imagem colorida de 64x64 pixels
largura = 64
altura = 64
canais_de_cor = 3  # RGB

# Gere uma imagem de exemplo (apenas para ilustração)
imagem_colorida = np.random.randint(0, 256, size=(largura, altura, canais_de_cor), dtype=np.uint8)

# Exibindo a forma da matriz
print("Forma da matriz da imagem:", imagem_colorida)

In [ ]:
# prompt: Verifique o shape de imagem_colorida

print("Forma da matriz da imagem:", imagem_colorida.shape)


Forma da matriz da imagem: (64, 64, 3)
